___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
my_arr = np.zeros(10)
my_arr[0:10]=5
my_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

My first solution was :
my_arr = np.arange(1,11)
my_arr[0:11]=5
my_arr
which results in array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [11]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
my_arr = np.arange(0,9)
my_arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [29]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [80]:
np.random.rand(1)

array([0.43890714])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [85]:
np.random.randn(25)

array([ 0.35117991, -0.42204405,  0.24993633, -0.66655737, -1.07957086,
        0.09494111,  0.05054123,  0.22342327,  0.30454366,  0.86682124,
        0.0140356 , -0.68350408, -0.05715793,  0.87913844, -0.21456485,
       -0.07083953, -0.50417654,  0.71762755, -0.58692033,  0.80864982,
        0.51959503, -0.25221961, -0.1933933 , -1.52975709, -1.36845028])

#### Create the following matrix:

In [104]:
my_arr = np.linspace(0.01,1,100)
my_arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

My first solution was just np.linspace(0.01,1,100) which resulted with this:
array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [106]:
np.linspace(0,1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [2]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

my_arr = np.arange(12,26)
slice1 = my_arr[0:4]
slice2 = my_arr[5:9]
slice3 = my_arr[10:14]

my_arr = np.array([slice1, slice2, slice3])
my_arr

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [184]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

my_arr[1][-1]

20

20

In [13]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

my_arr[:3, :1] - 10

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [110]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# I need to reset here as my_arr variable was a joined array through slices

my_arr = np.arange(12,26)
my_arr = my_arr.reshape(2, 7)
my_arr[1][2:7]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [166]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# my_arr latest output
# array([[12, 13, 14, 15, 16, 17, 18],
#       [19, 20, 21, 22, 23, 24, 25]])

# reshaped_arr = my_arr.reshape(1, 14)
# first_slice = reshaped_arr[:, 4:9]
# second_slice = reshaped_arr[:, 9:14]

# new_array = np.array([first_slice, second_slice])
# new_array

# output 
#array([[[16, 17, 18, 19, 20]],
#       [[21, 22, 23, 24, 25]]])

reshaped_arr = my_arr.reshape(-1)
first_slice = reshaped_arr[4:9]
second_slice = reshaped_arr[9:14]

new_array = np.array([first_slice, second_slice])
new_array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

### My answer:

In [4]:
# My first answer:

mat_result = mat[0] + mat[1] + mat[2] + mat[3] + mat[4]
mat_sum = mat_result[0] + mat_result[1] + mat_result[2] + mat_result[3] + mat_result[4]
mat_sum

# refactoring


    

325

#### Get the standard deviation of the values in mat

7.2111025509279782

### My Answer

In [6]:
item_total = mat.reshape(-1).shape[0]
mat_item = mat.reshape(-1)

# Step 2 divide total number of items to mat_sum
mat_mean = mat_sum/item_total

squared_item_results = []
for i in range(item_total):
    item_results = mat_item[i] - mat_mean
    squared_item_results.append(item_results**2)
    
# Step 3 find the sum of squared values regardless of sign (negative or positive)
sample_variance_numerator = sum(squared_item_results)

# Step 4 divide sample variance numerator to the items total minus 1
sample_variance = sample_variance_numerator/(item_total - 1)

# Step 5 find the square root of sample variance
import math
standard_deviation = math.sqrt(sample_variance)
standard_deviation

7.359800721939872

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

### My Answer

In [7]:
mat_result

array([55, 60, 65, 70, 75])

# Great Job!